/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddForm: typeof import('./src/components/common/AddForm/src/AddForm.vue')['default']
    BasicTitle: typeof import('./src/components/common/Form/src/components/BasicTitle.vue')['default']
    Cascader: typeof import('./src/components/common/Form/src/components/Cascader.vue')['default']
    CellRender: typeof import('./src/components/common/Table/src/components/cellRender.vue')['default']
    Checkbox: typeof import('./src/components/common/Form/src/components/Checkbox.vue')['default']
    Date: typeof import('./src/components/common/Form/src/components/Date.vue')['default']
    Dialog: typeof import('./src/components/common/Dialog/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Form: typeof import('./src/components/common/Form/src/Form.vue')['default']
    FormAction: typeof import('./src/components/common/Form/src/components/FormAction.vue')['default']
    FormItem: typeof import('./src/components/common/Form/src/components/FormItem.vue')['default']
    InitPage: typeof import('./src/components/business/InitPage/src/InitPage.vue')['default']
    Input: typeof import('./src/components/common/Form/src/components/Input.vue')['default']
    InputRange: typeof import('./src/components/common/Form/src/components/InputRange.vue')['default']
    Radio: typeof import('./src/components/common/Form/src/components/Radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./src/components/common/searchForm/src/searchForm.vue')['default']
    Select: typeof import('./src/components/common/Form/src/components/Select.vue')['default']
    SlotRender: typeof import('./src/components/common/Form/src/components/slotRender.vue')['default']
    Table: typeof import('./src/components/common/Table/src/Table.vue')['default']
    Upload: typeof import('./src/components/common/Form/src/components/Upload.vue')['default']
  }
}
