/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Form: typeof import('./src/components/common/Form/src/Form.vue')['default']
    FormAction: typeof import('./src/components/common/Form/src/components/FormAction.vue')['default']
    FormItem: typeof import('./src/components/common/Form/src/components/FormItem.vue')['default']
    Input: typeof import('./src/components/common/Form/src/components/Input.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/common/Form/src/components/Select.vue')['default']
    SlotRender: typeof import('./src/components/common/Form/src/components/slotRender.vue')['default']
  }
}
